package com.secureguard.enterprise.pennerkombat.model

import androidx.compose.ui.graphics.Color

object FighterDatabase {

    val fighters = listOf(
        Fighter(
            id = "le_binde",
            displayName = "Le Binde",
            nickName = "Der Schatten",
            description = "Ex-Legionär, lebt seit 12 Jahren auf der Straße. Seine Augenbinde verbirgt mehr als nur eine Narbe.",
            archetype = FighterArchetype.BRAWLER,
            maxHP = 105f,
            moveSpeed = 5.2f,
            lightDamage = 9f,
            heavyDamage = 17f,
            defense = 0.22f,
            special1 = SpecialMove("shadow_step", "Schatten Schritt", "Teleport hinter Gegner + 2x Hit", 18f, 6f, "👁️"),
            special2 = SpecialMove("binde_blitz", "Binden Blitz", "Wirft Augenbinde als Peitsche", 22f, 8f, "🩹"),
            fatality = "Binde stranguliert Gegner bis zum Platzen",
            brutality = "100 Schläge ohne Block in 15 Sek",
            colorPrimary = Color(0xFF1A1A1A),
            colorSecondary = Color(0xFF8B0000),
            emoji = "🧑‍🦯",
            story = "Le Binde war einst Elite-Soldat. Nach einem Verrat verlor er alles. Jetzt herrscht er über den Bahnhofsvorplatz.",
            tier = 4
        ),
        Fighter(
            id = "mell",
            displayName = "Mell",
            nickName = "Die Königin",
            description = "Ehemalige Opernsängerin mit Stimme wie zerbrochenes Glas. Ihr Einkaufswagen ist Waffe und Thron.",
            archetype = FighterArchetype.ZONER,
            maxHP = 95f,
            moveSpeed = 5.8f,
            lightDamage = 8f,
            heavyDamage = 14f,
            defense = 0.18f,
            special1 = SpecialMove("scream", "Opern Schrei", "Betäubt Gegner 1.2s, 3m Reichweite", 12f, 5f, "🎤"),
            special2 = SpecialMove("cart_crash", "Wagen Crash", "Rast mit Einkaufswagen durch Arena", 26f, 9f, "🛒"),
            fatality = "Einkaufswagen überrollt Kopf in SlowMo",
            brutality = "Gegner in 3 Einkaufswagen fallen lassen",
            colorPrimary = Color(0xFF6A0DAD),
            colorSecondary = Color(0xFFFFD700),
            emoji = "👑",
            story = "Mell beherrscht die Einkaufspassage. Wer ihr Revier betritt, zahlt Tribut – oder Blut.",
            tier = 5
        ),
        Fighter(
            id = "mojo_bob",
            displayName = "Mojo Bob",
            nickName = "Voodoo Penner",
            description = "Mischt Kräuter, Bier und Magie. Keiner weiß ob er verrückt oder erleuchtet ist.",
            archetype = FighterArchetype.TRICKSTER,
            maxHP = 100f,
            moveSpeed = 5.0f,
            lightDamage = 7.5f,
            heavyDamage = 16f,
            defense = 0.25f,
            special1 = SpecialMove("voodoo_doll", "Voodoo Puppe", "Linkt 40% Schaden zurück zum Gegner", 15f, 7f, "🪆"),
            special2 = SpecialMove("molle_curse", "Molle Fluch", "Gegner stolpert random, 5s Verwirrung", 10f, 6f, "🍺"),
            fatality = "Voodoo-Nadeln lassen Gegner implodieren",
            brutality = "5 Flüche gleichzeitig aktiv",
            colorPrimary = Color(0xFF2F4F4F),
            colorSecondary = Color(0xFF00FF7F),
            emoji = "🧙‍♂️",
            story = "Mojo Bob sieht Dinge die andere nicht sehen. Vielleicht weil er seit 3 Tagen nur Klebstoff geschnüffelt hat.",
            tier = 3
        ),
        Fighter(
            id = "dieter",
            displayName = "Dieter",
            nickName = "Der Schlosser",
            description = "30 Jahre Schlosser, jetzt schlägt er keine Nägel mehr sondern Köpfe ein. Hammer immer dabei.",
            archetype = FighterArchetype.TANK,
            maxHP = 125f,
            moveSpeed = 3.8f,
            lightDamage = 10f,
            heavyDamage = 20f,
            defense = 0.35f,
            special1 = SpecialMove("hammer_time", "Hammer Zeit", "Unblockbarer Overhead Hammer", 28f, 8f, "🔨"),
            special2 = SpecialMove("anvil_drop", "Amboss Drop", "Springt hoch, kracht runter – Shockwave", 24f, 10f, "⚒️"),
            fatality = "Hämmert Gegner wie glühendes Eisen platt",
            brutality = "3 Kills nur mit Hammer Specials",
            colorPrimary = Color(0xFF8B4513),
            colorSecondary = Color(0xFFA9A9A9),
            emoji = "👷",
            story = "Dieter hat seine Werkstatt verloren. Jetzt ist die Straße seine Werkbank.",
            tier = 4
        ),
        Fighter(
            id = "uschi",
            displayName = "Uschi",
            nickName = "Giftzahn",
            description = "Ehemalige Chemielaborantin. Ihre selbstgebraute Plörre ätzt Haut und Verstand.",
            archetype = FighterArchetype.ZONER,
            maxHP = 90f,
            moveSpeed = 6.0f,
            lightDamage = 7f,
            heavyDamage = 13f,
            defense = 0.15f,
            special1 = SpecialMove("acid_spit", "Säure Spucke", "DOT 8s, -20% Speed", 16f, 5f, "🧪"),
            special2 = SpecialMove("bottle_rain", "Flaschen Regen", "Wirft 6 Flaschen in Bogen", 20f, 7f, "🍾"),
            fatality = "Löst Gegner in Säurefass auf",
            brutality = "Gegner stirbt an DOT ohne direkten Hit",
            colorPrimary = Color(0xFF32CD32),
            colorSecondary = Color(0xFFFF1493),
            emoji = "🧑‍🔬",
            story = "Uschi wollte die Welt retten. Jetzt will sie nur noch, dass alle brennen wie sie.",
            tier = 3
        ),
        Fighter(
            id = "tetra_pak",
            displayName = "Tetra Pak",
            nickName = "Der Recycler",
            description = "Sammelt alles, wirft alles. Sein Mantel hat 47 Taschen voller Überraschungen.",
            archetype = FighterArchetype.TRICKSTER,
            maxHP = 110f,
            moveSpeed = 4.8f,
            lightDamage = 8.5f,
            heavyDamage = 15f,
            defense = 0.28f,
            special1 = SpecialMove("trash_tornado", "Müll Tornado", "Wirbel aus Müll, zieht Gegner rein", 21f, 7f, "🌪️"),
            special2 = SpecialMove("pak_schild", "Tetra Schild", "Baut Schild aus Paketen, reflektiert 60%", 0f, 8f, "📦"),
            fatality = "Erstickt Gegner in Müllsack",
            brutality = "Gegner mit 20 verschiedenen Items treffen",
            colorPrimary = Color(0xFF4682B4),
            colorSecondary = Color(0xFFD2691E),
            emoji = "📦",
            story = "Tetra Pak hat alles verloren außer seinem Sammeltrieb. Jetzt sammelt er Zähne.",
            tier = 2
        ),
        Fighter(
            id = "sigi",
            displayName = "Sigi",
            nickName = "Zitter Sigi",
            description = "Parkinson und Wut – unberechenbare Zitter-Hits die keiner blocken kann.",
            archetype = FighterArchetype.SPEED,
            maxHP = 85f,
            moveSpeed = 6.5f,
            lightDamage = 6f,
            heavyDamage = 12f,
            defense = 0.12f,
            special1 = SpecialMove("zitter_sturm", "Zitter Sturm", "12 Hits in 0.8s, unblockbar", 24f, 6f, "⚡"),
            special2 = SpecialMove("flatter", "Flatter Mann", "Teleport 5x random, letzter Hit kritisch", 19f, 7f, "💨"),
            fatality = "Zittert Gegner in Einzelteile",
            brutality = "50 Hits Combo ohne Heavy",
            colorPrimary = Color(0xFF708090),
            colorSecondary = Color(0xFFFFFF00.toInt()),
            emoji = "🥴",
            story = "Sigi zittert nicht vor Angst. Er zittert vor Lust auf den nächsten Kampf.",
            tier = 5
        ),
        Fighter(
            id = "rolf",
            displayName = "Rolf",
            nickName = "Bier-Rolf",
            description = "Dauertank mit 3,2 Promille als Normalzustand. Je betrunkener, desto gefährlicher.",
            archetype = FighterArchetype.TANK,
            maxHP = 130f,
            moveSpeed = 3.5f,
            lightDamage = 11f,
            heavyDamage = 18f,
            defense = 0.40f,
            special1 = SpecialMove("bier_bauch", "Bier Bauch", "Bauchplatscher, betäubt 2s", 20f, 6f, "🍻"),
            special2 = SpecialMove("rülps", "Atom Rülpser", "Giftwolke 4m, DOT + Slow", 14f, 5f, "💨"),
            fatality = "Ertränkt Gegner in Bierfass",
            brutality = "Gegner besiegen während man selbst betrunken ist",
            colorPrimary = Color(0xFFFF8C00),
            colorSecondary = Color(0xFF8B0000),
            emoji = "🍺",
            story = "Rolf hat seit 1998 nicht mehr nüchtern gekämpft. Warum auch?",
            tier = 2
        ),
        Fighter(
            id = "kalle",
            displayName = "Kalle",
            nickName = "Der Hund",
            description = "Hat 3 Hunde, spricht nur mit ihnen. Hunde kämpfen mit.",
            archetype = FighterArchetype.BRAWLER,
            maxHP = 100f,
            moveSpeed = 5.5f,
            lightDamage = 9.5f,
            heavyDamage = 16f,
            defense = 0.20f,
            special1 = SpecialMove("hunde_rudel", "Rudel Ruf", "3 Hunde greifen an, 3s Stun", 23f, 9f, "🐕"),
            special2 = SpecialMove("knochen_wurf", "Knochen Wurf", "Hunde jagen Knochen zum Gegner", 18f, 6f, "🦴"),
            fatality = "Hunde zerreißen Gegner",
            brutality = "Gegner ohne selbst zu schlagen (nur Hunde) besiegen",
            colorPrimary = Color(0xFF556B2F),
            colorSecondary = Color(0xFF8B4513),
            emoji = "🐶",
            story = "Kalle vertraut nur seinen Hunden. Und die hassen alle außer Kalle.",
            tier = 3
        )
    )

    val trophies = listOf(
        Trophy("first_blood", "Erstes Blut", "Gewinne deinen ersten Kampf", "🩸", "Bronze"),
        Trophy("combo_10", "Combo König", "10er Combo", "🔥", "Bronze"),
        Trophy("combo_25", "Combo Gott", "25er Combo", "💥", "Gold"),
        Trophy("fatality_1", "Finisher", "Erste Fatality", "💀", "Silber"),
        Trophy("fatality_all", "Serienmörder", "Alle Fatalities", "☠️", "Platin"),
        Trophy("no_damage", "Unberührbar", "Runde ohne Schaden gewinnen", "🛡️", "Gold"),
        Trophy("story_complete", "Straßenlegende", "Story Modus durchspielen", "👑", "Gold"),
        Trophy("all_chars", "Sammler", "Alle 9 Charaktere freischalten", "📦", "Silber"),
        Trophy("mops", "Mops Alarm", "Mops triggert Arena Event", "🐶", "Bronze"),
        Trophy("beer_crate", "Bierkasten Killer", "Gegner mit Bierkasten KO", "🍺", "Bronze"),
        Trophy("perfect", "Perfekt", "Perfect Win (100% HP)", "✨", "Gold"),
        Trophy("rage", "Raserei", "5 Kämpfe in Folge gewinnen", "😡", "Silber")
    )

    val storyChapters = listOf(
        StoryChapter(1, "Ankunft", "Du kommst neu an den Bahnhof. Le Binde testet dich.", "le_binde", listOf("Wer bist du? Hier herrsche ich.", "Mal sehen ob du was taugst, Frischling!"), "Freischaltung: Le Binde Moveset", false),
        StoryChapter(2, "Die Königin", "Mell will Tribut. Zahlst du mit Blut oder Bier?", "mell", listOf("Mein Revier, meine Regeln, Süßer.", "Deine Fresse oder deine Flasche – such's dir aus!"), "Freischaltung: Einkaufswagen Waffe", false),
        StoryChapter(3, "Voodoo", "Mojo Bob sieht deine Zukunft. Sie ist kurz.", "mojo_bob", listOf("Die Geister sagen... du stirbst heute.", "Klebstoff macht sehend, Kleiner."), "Freischaltung: Voodoo Schutz", false),
        StoryChapter(4, "Der Schlosser", "Dieter braucht Material. Deine Knochen.", "dieter", listOf("30 Jahre hab ich Eisen gebogen. Jetzt bieg ich dich.", "Komm her, ich hab nen Hammer für dich."), "Freischaltung: Hammer", true),
        StoryChapter(5, "Gift", "Uschi hat gebraut. Willst du kosten?", "uschi", listOf("Das riecht nach... Tod. Lecker, oder?", "Ein Schluck und du siehst Farben!"), "Freischaltung: Säure Resistenz", false),
        StoryChapter(6, "Müllhalde", "Tetra Pak verteidigt seinen Berg.", "tetra_pak", listOf("Alles meins! Alles!", "Ich sammel auch deine Zähne gleich."), "Freischaltung: Recycling Rüstung", false),
        StoryChapter(7, "Zittern", "Sigi kann nicht aufhören. Auch nicht zu schlagen.", "sigi", listOf("Z-z-zitter nicht... ich... ARGHH!", "Schneller! Schneller! SCHNELLER!"), "Freischaltung: Speed Boost", false),
        StoryChapter(8, "Das Finale", "Alle gegen dich. Der Bahnhof gehört dem Stärksten.", "rolf", listOf("Jetzt reicht's! Alle gegen den Neuen!", "Wer hier bleiben will, muss uns alle schlagen!"), "Ende: Straßenkönig", true)
    )

    fun getById(id: String) = fighters.find { it.id == id } ?: fighters.first()
}
